******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>
//
//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
//
//int main(void)
//{
//    /* Loop forever */
//	for(;;);
//}

#include "stm32f4xx.h"

#define GPIOAEN  (1U<<0)
#define PIN5     (1U<<5)
#define LED_PIN  PIN5

int main()
{
	/*Enable clock access to GPIO A */
	RCC->AHB1ENR |= GPIOAEN;

	GPIOA -> MODER |= (1U<<10);
	GPIOA -> MODER &=~(1U<<11);
	while(1)
	{
		GPIOA ->ODR ^=LED_PIN;
		for(int i=0;i<100000;i++){

		}
	}
}
